### ISSUE TITLE
MacOS build fail with GLUT Fatal Error

### ISSUE THREAD

**Issue by selimanac** [ic-pcg/waveFunctionCollapse#1]
I'm trying to build on MacOS but having a issue with GLUT.
I searched but couldn't find a proper solution. Any idea why is this happens? 

`GLUT Fatal Error: internal error: NSInternalInconsistencyException, reason: NSWindow drag regions should only be invalidated on the Main Thread!`

Thank you

**Comment by selimanac** [comment]
Btw, It runs fine on main thread. I guess it is a GLUT problem on MacOS. Feel free to close the issue if you don't want to research.

```
//  pthread_create(&graphics_id, NULL, runGraphics, (void*)&main_arguments);
    runGraphics((void*)&main_arguments);
```

**Comment by woocashh** [comment]
Hi Selim!

Thank you for giving our code a try, real honour! 

We have needed some time to get it to work on Mac (only one team member has an old one). We have not faced similar issues, but thank you for coming up with one possible solution. We have included a guide for macOS users in the README today, maybe you can find it helpful (there is one Segfault but it does not affect the working of the program).

**Comment by selimanac** [comment]
@woocashh Thank you, work like a charm.

I can suggest a few small changes (or I can PR if you like):

- On `graphicsRunner.h` includes can be like this (samething can be used for sleep(10) on run_wfc.c)

```cpp
#ifdef __APPLE__
/* Defined before OpenGL and GLUT includes to avoid deprecation messages */
#define GL_SILENCE_DEPRECATION
#include <OpenGL/gl.h>
#include <GLUT/glut.h>
#include <OpenGL/glu.h>
#else
#include <GL/gl.h>
#include <GL/glu.h>
#include <GL/glut.h>
#endif
```
- And for the make files

```bash
UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S), Linux) #LINUX
	CFLAGS = ...
endif


ifeq ($(UNAME_S), Darwin) #APPLE
	CFLAGS = ...
endif

```

**Comment by woocashh** [comment]
This is now done, should be more convenient on MacOS!
