### ISSUE TITLE
About the license...

### ISSUE THREAD

**Issue by selimanac** [ic-pcg/waveFunctionCollapse#2]
I'm planning to implement this project(by given you a proper credits of course) as a free(open source) C native extension to [Defold](https://defold.com/) game engine. 
I couldn't find any license info. Is it MIT? Do you have any license/usage restriction?

**Comment by woocashh** [comment]
Dear Selim,

It is MIT :) Feel free to use it :D Happy to help!

**Comment by woocashh** [comment]
Just remember that:
Tile art in graphics/rpg_map is Overworld rpg tileset by Tayoko (licensed under CC BY-SA 3.0) available at opengameart.org/content/overworld-rpg-tileset

**Comment by selimanac** [comment]
> Tile art in graphics/rpg_map is Overworld rpg tileset by Tayoko (licensed under CC BY-SA 3.0) available at opengameart.org/content/overworld-rpg-tileset

Ok. Thank you :)
